[package]
name = "tricoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rayon = "1.5"
reqwest = "0.11"
serde = "1"
thiserror = "1.0"
trust-dns-resolver = "0.21"
